server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: movieService
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: catalogService
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
